### ISSUE TITLE
这怎么用？

### ISSUE THREAD

**Issue by zhaokuohaha** [wolfogre/ss-user-rule#1]
组长我看了下txt, 是adblock的?  大略浏览了一下好像跟你txt里面的不一样
这个文件不是用给ss的么?

**Comment by wolfogre** [comment]
是给 SS 用的，用户自定义的走代理的规则，语法借用 adblock 的。
![default](https://user-images.githubusercontent.com/9418365/38775876-b42473ec-40bf-11e8-89ed-4c56a204b795.PNG)
因为我家里的宽带恶意阻断了一些不在GFW列表里的网站，公司的网也会监控一些不属于GFW列表的网站。所以我写了一些自定义规则，分2个branch，在不同场景里用。

**Comment by zhaokuohaha** [comment]
相当于这是对默认规则的一个补充？

**Comment by wolfogre** [comment]
dei~
